name: Trello RSS to GitHub

on:
  workflow_dispatch:  # This allows you to trigger it manually

jobs:
  post-to-trello:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "Hello from GitHub Actions!"
